### PR TITLE
Add keybinds to Q OS master branch

### PR DESCRIPTION
**Pull request by raphydaphy**
I looked at some of the work in plankp's fork and it's really good.

Do you want to merge our branches and work on the code together in the master branch?

### CODE REVIEW

**Comment by plankp** [comment]
:+1:

**Comment by plankp** [comment]
How do you build the iso?

**Comment by raphydaphy** [comment]
nasm -f elf32 kernel.asm -o kernel.asm.o
    gcc -m32 -c kernel.c -o kernel.c.o -ffreestanding                                                                     
    gcc -m32 -c inc/assemblyFunctions.c -o o/assemblyFunctions.o -ffreestanding                                                     
    gcc -m32 -c inc/stringUtils.c -o o/stringUtils.o -ffreestanding                                                     
    gcc -m32 -c inc/screenUtils.c -o o/screenUtils.o -ffreestanding                                                     
    gcc -m32 -c inc/kbDetect.c -o o/kbDetect.o -ffreestanding                                                             
    ld -m elf_i386 -T link.ld -o q/boot/kernel.bin kernel.asm.o kernel.c.o o/assemblyFunctions.o    o/stringUtils.o o/screenUtils.o o/kbDetect.o  
    grub-mkrescue -o q.iso q/

**Comment by raphydaphy** [comment]
If you are using a <code>apt-get</code> system, you can do this to get all the packages needed to build it:

    sudo apt-get install xorriso grub gcc nasm virtualbox geddit

**Comment by plankp** [comment]
It says mtools or something not found at grub-mkrescue

**Comment by raphydaphy** [comment]
You need to install the packages first, what OS are you using

**Comment by plankp** [comment]
Manjaro (Arch Linux)
Should I Ubuntu fresh install?

**Comment by raphydaphy** [comment]
Yea if you want, I use Fedora on my Mac Pro and Ubuntu on my macbook , but Ubuntu is best for OS development except it dosent work on my mac pro :cry:

**Comment by plankp** [comment]
k

**Comment by raphydaphy** [comment]
should i merge this pull request or do you want to keep your fork by itself until you can build it?

**Comment by plankp** [comment]
I've been qemu-ing

**Comment by plankp** [comment]
so its tested

**Comment by raphydaphy** [comment]
cool :+1:

**Comment by raphydaphy** [comment]
Do you have read write access to the master branch now ? Your meant to because I added you as a contributed but idk if it worked :worried:

**Comment by plankp** [comment]
I think it did. Went on the contributed repos list

**Comment by raphydaphy** [comment]
:+-:

**Comment by christopherpow** [comment]
It's strange to have C files in inc folder.

**Comment by plankp** [comment]
Only .h files in `inc`?

**Comment by plankp** [comment]
I will keep using my own repo and merge request I think

**Comment by raphydaphy** [comment]
Do you want to only have .h in <code>/kernel/inc/</code> and all .c files in <code>/kernel/</code>?

**Comment by plankp** [comment]
ask @christopherpow

**Comment by raphydaphy** [comment]
Ok :+1: 

@christopherpow  do you think we should move the .c files so we only have .h in /kernel/inc/ and all .c files in /kernel/?

**Pull request merged**
